language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
  - "iojs"
  - "iojs-v1.0.4"
matrix:
  allow_failures:
    - node_js: "0.8"
    - node_js: "0.6"
before_script:
  - npm install -g jake